version: '3.8'

services:
  api:
    build: .
    ports:
      - '8090:8090'
    container_name: bookapi
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customers
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
    depends_on:
      - db
    networks:
      app:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: customers
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 6432:5432
    networks:
      app:
volumes:
  db-data:
    driver: local
networks:
  app:
    driver: bridge