INSERT INTO CLIENTS (NAME, COMPANY_ID) VALUES ('Петр Булочкин', 1);
INSERT INTO CLIENTS (NAME, COMPANY_ID) VALUES ('Федор', 2);
INSERT INTO CLIENTS (NAME, COMPANY_ID) VALUES ('Джонни Уокер', 2);
INSERT INTO COMPANIES (COMPANY_NAME) VALUES ('АО РОМАШКА');
INSERT INTO COMPANIES (COMPANY_NAME) VALUES ('АО БУХАНКА');
INSERT INTO COMPANIES (COMPANY_NAME) VALUES ('АО БУХАНКА');