INSERT INTO COMPANY (COMPANY_NAME, ID) VALUES ('АО РОМАШКА', 1);
INSERT INTO COMPANY (COMPANY_NAME, ID) VALUES ('АО БУХАНКА', 2);
INSERT INTO COMPANY (COMPANY_NAME, ID) VALUES ('АО БУЛОЧКА', 3);
INSERT INTO CLIENT (NAME, ID, COMPANY_ID) VALUES ('Петр Булочкин', 1, 2);
INSERT INTO CLIENT (NAME, ID, COMPANY_ID) VALUES ('Федор', 2, 3);
INSERT INTO CLIENT (NAME, ID, COMPANY_ID) VALUES ('Джонни Уокер', 3, 2);