drop table IF EXISTS CLIENTS CASCADE;
create TABLE IF NOT EXISTS CLIENTS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    COMPANY_ID INTEGER CHECK (COMPANY_ID > 0)
    );
    drop table IF EXISTS COMPANIES;
create table IF NOT EXISTS COMPANIES (
ID SERIAL PRIMARY KEY,
COMPANY_NAME VARCHAR(255));